export const generatedAtlasCharacters = [
  {
    id: "auto-0001-a35093e97c",
    name: "元莲仙尊",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 171 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 171, count: 343, regionLabel: "中洲" },
  },
  {
    id: "auto-0002-ec8450b4e9",
    name: "元始仙尊",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 615 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 615, count: 378, regionLabel: "中洲" },
  },
  {
    id: "auto-0003-8cd04ea0e2",
    name: "长毛老祖",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 471 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 471, count: 356, regionLabel: "北原" },
  },
  {
    id: "auto-0004-65f58166fe",
    name: "绿蚁居士",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1851 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1851, count: 46, regionLabel: "中洲" },
  },
  {
    id: "auto-0005-7acc3c3f9c",
    name: "明皓仙子",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 2182 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2182, count: 94, regionLabel: "中洲" },
  },
  {
    id: "auto-0006-fc7650950b",
    name: "万寿娘子",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 830 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 830, count: 13, regionLabel: "北原" },
  },
  {
    id: "auto-0007-243b28eb92",
    name: "幻灭仙子",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 967 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 967, count: 4, regionLabel: "中洲" },
  },
  {
    id: "auto-0008-824385b18a",
    name: "白晴仙子",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 417 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 417, count: 246, regionLabel: "中洲" },
  },
  {
    id: "auto-0009-69a74509e7",
    name: "盗天魔尊",
    region: "western",
    faction: "西漠归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 445 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 445, count: 635, regionLabel: "西漠" },
  },
  {
    id: "auto-0010-81ac35e1e8",
    name: "琅琊地灵",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 472 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 472, count: 3215, regionLabel: "北原" },
  },
  {
    id: "auto-0011-6401c9d90c",
    name: "凤仙太子",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 753 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 753, count: 769, regionLabel: "北原" },
  },
  {
    id: "auto-0012-48ddf5be57",
    name: "白兔姑娘",
    region: "southern",
    faction: "南疆归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1233 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1233, count: 461, regionLabel: "南疆" },
  },
  {
    id: "auto-0013-a40e2b2844",
    name: "雷鬼真君",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1575 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1575, count: 273, regionLabel: "中洲" },
  },
  {
    id: "auto-0014-106e40afab",
    name: "焚天魔女",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 760 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 760, count: 12, regionLabel: "北原" },
  },
  {
    id: "auto-0015-1de39f22cd",
    name: "冰晶仙王",
    region: "black",
    faction: "太古黑天归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入太古黑天。首次出现第 1991 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1991, count: 12, regionLabel: "太古黑天" },
  },
  {
    id: "auto-0016-54e3becb96",
    name: "花酒行者",
    region: "southern",
    faction: "南疆归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 12 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 12, count: 208, regionLabel: "南疆" },
  },
  {
    id: "auto-0017-a44a2ea22f",
    name: "天鹤上人",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 200 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 200, count: 508, regionLabel: "中洲" },
  },
  {
    id: "auto-0018-9e05e367ad",
    name: "紫山真君",
    region: "southern",
    faction: "南疆归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 629 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 629, count: 1009, regionLabel: "南疆" },
  },
  {
    id: "auto-0019-ef2a13e61b",
    name: "雪胡老祖",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 652 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 652, count: 893, regionLabel: "北原" },
  },
  {
    id: "auto-0020-bc6fcc51c2",
    name: "无极魔尊",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 955 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 955, count: 510, regionLabel: "中洲" },
  },
  {
    id: "auto-0021-624bda19d0",
    name: "妙音仙子",
    region: "southern",
    faction: "南疆归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1234 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1234, count: 423, regionLabel: "南疆" },
  },
  {
    id: "auto-0022-65ff348529",
    name: "骷髅姥姥",
    region: "white",
    faction: "太古白天归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入太古白天。首次出现第 1997 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1997, count: 3, regionLabel: "太古白天" },
  },
  {
    id: "auto-0023-0e261f0015",
    name: "萧荷尖",
    region: "black",
    faction: "太古黑天归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入太古黑天。首次出现第 2019 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2019, count: 19, regionLabel: "太古黑天" },
  },
  {
    id: "auto-0024-7f18bba1c4",
    name: "黄史上人",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1425 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1425, count: 145, regionLabel: "中洲" },
  },
  {
    id: "auto-0025-a0ee02f64a",
    name: "狂蛮魔尊",
    region: "unverified",
    faction: "地域待考",
    role: "全文人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 611 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 611, count: 156, regionLabel: "待考" },
  },
  {
    id: "auto-0026-9e5a698d52",
    name: "毓秀仙子",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 2190 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2190, count: 90, regionLabel: "中洲" },
  },
  {
    id: "auto-0027-4f371d0ee8",
    name: "苏白曼",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 763 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 763, count: 15, regionLabel: "东海" },
  },
  {
    id: "auto-0028-496d5166a4",
    name: "多宝真人",
    region: "unverified",
    faction: "地域待考",
    role: "全文人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 477 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 477, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0029-f1bf082eaa",
    name: "空绝老仙",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 612 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 612, count: 11, regionLabel: "中洲" },
  },
  {
    id: "auto-0030-dfca631f6d",
    name: "苍郁仙子",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 684 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 684, count: 61, regionLabel: "中洲" },
  },
  {
    id: "auto-0031-ca973f9e12",
    name: "翠波仙子",
    region: "western",
    faction: "西漠归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1415 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1415, count: 96, regionLabel: "西漠" },
  },
  {
    id: "auto-0032-e803268f63",
    name: "花蝶女仙",
    region: "eastern",
    faction: "东海归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1172 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1172, count: 23, regionLabel: "东海" },
  },
  {
    id: "auto-0033-947b1cebad",
    name: "大梦仙尊",
    region: "unverified",
    faction: "地域待考",
    role: "全文人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 472 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 472, count: 81, regionLabel: "待考" },
  },
  {
    id: "auto-0034-fee4db2292",
    name: "狐仙地灵",
    region: "central",
    faction: "中洲归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 374 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 374, count: 35, regionLabel: "中洲" },
  },
  {
    id: "auto-0035-1b081c67e0",
    name: "火原洞主",
    region: "white",
    faction: "太古白天归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入太古白天。首次出现第 2129 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2129, count: 52, regionLabel: "太古白天" },
  },
  {
    id: "auto-0036-666ea49108",
    name: "姜钰",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 707 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 707, count: 138, regionLabel: "北原" },
  },
  {
    id: "auto-0037-1331e3d613",
    name: "萧家老祖",
    region: "western",
    faction: "西漠归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 980 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 980, count: 9, regionLabel: "西漠" },
  },
  {
    id: "auto-0038-ac594b0e96",
    name: "江牙",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 20 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 20, count: 5, regionLabel: "南疆" },
  },
  {
    id: "auto-0039-2146b17869",
    name: "贾金生",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 50 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 50, count: 13, regionLabel: "南疆" },
  },
  {
    id: "auto-0040-e4d25eced6",
    name: "百八十奴",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1395 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1395, count: 2, regionLabel: "东海" },
  },
  {
    id: "auto-0041-1a314f88e5",
    name: "古月空井",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 96 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 96, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0042-d7eb852c9d",
    name: "阳骏",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1713 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1713, count: 1, regionLabel: "东海" },
  },
  {
    id: "auto-0043-2626e3cf7a",
    name: "古月方想",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 2273 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2273, count: 3, regionLabel: "待考" },
  },
  {
    id: "auto-0044-e8ceb82e1f",
    name: "林大鸟",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 949 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 949, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0045-9425674797",
    name: "叶凡",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 696 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 696, count: 33, regionLabel: "南疆" },
  },
  {
    id: "auto-0046-3eb9bcca5a",
    name: "东方长凡",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 675 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 675, count: 22, regionLabel: "北原" },
  },
  {
    id: "auto-0047-7a4436c6d5",
    name: "商一帆",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 330 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 330, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0048-85e813b476",
    name: "百草率",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 225 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 225, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0049-83be1bfaa4",
    name: "百陌亭",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 225 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 225, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0050-2385b476d9",
    name: "百盛景",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 226 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 226, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0051-d8f7cecb06",
    name: "史宏",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 846 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 846, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0052-471aee99ea",
    name: "二毛",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 900 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 900, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0053-ef52a5e53e",
    name: "黑心道人",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1739 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1739, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0054-a1ef37ebf2",
    name: "钟义",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 2126 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2126, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0055-1c80a6db15",
    name: "白沧水",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 889 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 889, count: 20, regionLabel: "中洲" },
  },
  {
    id: "auto-0056-e1538559ad",
    name: "童画",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1321 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1321, count: 38, regionLabel: "东海" },
  },
  {
    id: "auto-0057-a5723af7e7",
    name: "宋紫星",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 722 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 722, count: 25, regionLabel: "中洲" },
  },
  {
    id: "auto-0058-a4cbb93d1d",
    name: "秦鼎菱",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1847 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1847, count: 59, regionLabel: "中洲" },
  },
  {
    id: "auto-0059-a356662cec",
    name: "厉煌",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1654 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1654, count: 44, regionLabel: "中洲" },
  },
  {
    id: "auto-0060-dab9be0319",
    name: "秦百胜",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 693 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 693, count: 43, regionLabel: "北原" },
  },
  {
    id: "auto-0061-ec33913fa1",
    name: "陈衣",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1530 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1530, count: 39, regionLabel: "中洲" },
  },
  {
    id: "auto-0062-8fb3a9f170",
    name: "沈伤",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1930 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1930, count: 36, regionLabel: "东海" },
  },
  {
    id: "auto-0063-b7ad490ebf",
    name: "韩立",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 688 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 688, count: 13, regionLabel: "西漠" },
  },
  {
    id: "auto-0064-317cb311ae",
    name: "墨瑶",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 581 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 581, count: 26, regionLabel: "中洲" },
  },
  {
    id: "auto-0065-ab0a73ad5a",
    name: "乔丝柳",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1238 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1238, count: 23, regionLabel: "南疆" },
  },
  {
    id: "auto-0066-16be5e792c",
    name: "人祖",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 13 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 13, count: 20, regionLabel: "待考" },
  },
  {
    id: "auto-0067-1593ddb90b",
    name: "池曲由",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1402 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1402, count: 27, regionLabel: "南疆" },
  },
  {
    id: "auto-0068-3f898c739e",
    name: "百莲",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 225 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 225, count: 7, regionLabel: "待考" },
  },
  {
    id: "auto-0069-b9144c1c04",
    name: "古月阴荒",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 189 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 189, count: 6, regionLabel: "南疆" },
  },
  {
    id: "auto-0070-ff63629c57",
    name: "君神光",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1626 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1626, count: 5, regionLabel: "中洲" },
  },
  {
    id: "auto-0071-df5d3eee67",
    name: "常丽",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 591 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 591, count: 8, regionLabel: "北原" },
  },
  {
    id: "auto-0072-e077887457",
    name: "赤舌",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 101 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 101, count: 3, regionLabel: "待考" },
  },
  {
    id: "auto-0073-9bf4c845f7",
    name: "江鹤",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 77 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 77, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0074-30eb3727da",
    name: "苏仙儿",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 539 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 539, count: 3, regionLabel: "北原" },
  },
  {
    id: "auto-0075-6d57e74faa",
    name: "房棱",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1526 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1526, count: 36, regionLabel: "西漠" },
  },
  {
    id: "auto-0076-b15b505756",
    name: "毛六",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 1092 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1092, count: 23, regionLabel: "北原" },
  },
  {
    id: "auto-0077-71c3a2476f",
    name: "商睚眦",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 270 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 270, count: 9, regionLabel: "南疆" },
  },
  {
    id: "auto-0078-be2827755e",
    name: "薄青",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 972 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 972, count: 23, regionLabel: "中洲" },
  },
  {
    id: "auto-0079-42b82d2f8f",
    name: "万紫红",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1737 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1737, count: 21, regionLabel: "中洲" },
  },
  {
    id: "auto-0080-07ba78b6e4",
    name: "百足天君",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 781 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 781, count: 12, regionLabel: "北原" },
  },
  {
    id: "auto-0081-3a40abafc4",
    name: "鹤风扬",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 219 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 219, count: 15, regionLabel: "中洲" },
  },
  {
    id: "auto-0082-d13ded15bb",
    name: "白相",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1053 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1053, count: 40, regionLabel: "南疆" },
  },
  {
    id: "auto-0083-713883f120",
    name: "贺狼子",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 768 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 768, count: 17, regionLabel: "北原" },
  },
  {
    id: "auto-0084-3e514702f0",
    name: "任修平",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1174 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1174, count: 16, regionLabel: "东海" },
  },
  {
    id: "auto-0085-6b13f750da",
    name: "宋启元",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1712 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1712, count: 18, regionLabel: "东海" },
  },
  {
    id: "auto-0086-c08fb2ea24",
    name: "房云",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1526 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1526, count: 17, regionLabel: "西漠" },
  },
  {
    id: "auto-0087-f5674ab2a1",
    name: "古月博",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 66 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 66, count: 16, regionLabel: "南疆" },
  },
  {
    id: "auto-0088-602d92b8b4",
    name: "车尾",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1739 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1739, count: 18, regionLabel: "中洲" },
  },
  {
    id: "auto-0089-5ae0fde4dd",
    name: "陈鑫",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 242 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 242, count: 3, regionLabel: "待考" },
  },
  {
    id: "auto-0090-8487133444",
    name: "皮水寒",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 799 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 799, count: 19, regionLabel: "北原" },
  },
  {
    id: "auto-0091-792b1d0019",
    name: "古月赤练",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 12 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 12, count: 13, regionLabel: "南疆" },
  },
  {
    id: "auto-0092-f1f800e9bf",
    name: "自在书生",
    region: "northern",
    faction: "北原归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 768 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 768, count: 5, regionLabel: "北原" },
  },
  {
    id: "auto-0093-9ff1b5b1f6",
    name: "庙明神",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1317 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1317, count: 18, regionLabel: "东海" },
  },
  {
    id: "auto-0094-3b4934acef",
    name: "洪易",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 691 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 691, count: 15, regionLabel: "待考" },
  },
  {
    id: "auto-0095-65d46853da",
    name: "夏槎",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1621 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1621, count: 14, regionLabel: "南疆" },
  },
  {
    id: "auto-0096-330c9120da",
    name: "魏央",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 272 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 272, count: 12, regionLabel: "南疆" },
  },
  {
    id: "auto-0097-edd5508f21",
    name: "苏琪涵",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 1892 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1892, count: 11, regionLabel: "中洲" },
  },
  {
    id: "auto-0098-b0afe2ec3a",
    name: "马尊",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 449 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 449, count: 13, regionLabel: "北原" },
  },
  {
    id: "auto-0099-3eda5609ae",
    name: "古月药红",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 90 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 90, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0100-f9487d7d96",
    name: "张阴",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1712 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1712, count: 11, regionLabel: "东海" },
  },
  {
    id: "auto-0101-e4cf87a9a8",
    name: "李然",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 288 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 288, count: 14, regionLabel: "南疆" },
  },
  {
    id: "auto-0102-c98421e2b3",
    name: "古月药姬",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 85 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 85, count: 12, regionLabel: "南疆" },
  },
  {
    id: "auto-0103-0ac3ce8594",
    name: "古月青书",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 147 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 147, count: 12, regionLabel: "南疆" },
  },
  {
    id: "auto-0104-0798931243",
    name: "古月一代",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 192 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 192, count: 10, regionLabel: "南疆" },
  },
  {
    id: "auto-0105-ea73001be3",
    name: "巴十八",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1748 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1748, count: 10, regionLabel: "南疆" },
  },
  {
    id: "auto-0106-792dde5da8",
    name: "寒灰仙姑",
    region: "black",
    faction: "太古黑天归档",
    role: "全文人物",
    intro: "原文人物档案，按出身或主要势力根基归入太古黑天。首次出现第 1991 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1991, count: 4, regionLabel: "太古黑天" },
  },
  {
    id: "auto-0107-ab29bac128",
    name: "毛十二",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 903 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 903, count: 12, regionLabel: "北原" },
  },
  {
    id: "auto-0108-9461b5d46f",
    name: "石宗",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1480 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1480, count: 14, regionLabel: "待考" },
  },
  {
    id: "auto-0109-6c548409ec",
    name: "万象星君",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 681 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 681, count: 8, regionLabel: "中洲" },
  },
  {
    id: "auto-0110-168ae9e260",
    name: "熊力",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 129 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 129, count: 7, regionLabel: "南疆" },
  },
  {
    id: "auto-0111-f429a0d9f5",
    name: "张柱",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 246 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 246, count: 6, regionLabel: "南疆" },
  },
  {
    id: "auto-0112-339ca8dfd8",
    name: "商青青",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1129 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1129, count: 4, regionLabel: "南疆" },
  },
  {
    id: "auto-0113-973f02da35",
    name: "容婆",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1710 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1710, count: 11, regionLabel: "东海" },
  },
  {
    id: "auto-0114-970fe15ed0",
    name: "古月漠尘",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 29 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 29, count: 6, regionLabel: "南疆" },
  },
  {
    id: "auto-0115-ff8d9782c8",
    name: "池伤",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1349 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1349, count: 14, regionLabel: "南疆" },
  },
  {
    id: "auto-0116-ef56109f0b",
    name: "曾落子",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1672 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1672, count: 10, regionLabel: "东海" },
  },
  {
    id: "auto-0117-0a97a787a2",
    name: "卫德馨",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 338 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 338, count: 11, regionLabel: "南疆" },
  },
  {
    id: "auto-0118-fa3033e66e",
    name: "乔志材",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1360 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1360, count: 10, regionLabel: "南疆" },
  },
  {
    id: "auto-0119-a5a6542b97",
    name: "萧芒",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 402 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 402, count: 9, regionLabel: "南疆" },
  },
  {
    id: "auto-0120-3c92d0d42e",
    name: "武八重",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 2009 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 2009, count: 8, regionLabel: "南疆" },
  },
  {
    id: "auto-0121-01f924b589",
    name: "常极右",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 546 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 546, count: 7, regionLabel: "北原" },
  },
  {
    id: "auto-0122-92035ebae4",
    name: "易酒仙姑",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1851 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1851, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0123-d6a6fdb33b",
    name: "萧山",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 980 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 980, count: 10, regionLabel: "南疆" },
  },
  {
    id: "auto-0124-720c714915",
    name: "熊姜",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 129 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 129, count: 4, regionLabel: "南疆" },
  },
  {
    id: "auto-0125-74019928e2",
    name: "古月赤城",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 12 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 12, count: 6, regionLabel: "南疆" },
  },
  {
    id: "auto-0126-43671c4a4a",
    name: "古月漠北",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 12 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 12, count: 8, regionLabel: "南疆" },
  },
  {
    id: "auto-0127-1a85016b9c",
    name: "夏飞快",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1328 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1328, count: 8, regionLabel: "南疆" },
  },
  {
    id: "auto-0128-1da783cd55",
    name: "熊林",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 143 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 143, count: 5, regionLabel: "南疆" },
  },
  {
    id: "auto-0129-f2a1e119a0",
    name: "房化生",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1549 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1549, count: 5, regionLabel: "西漠" },
  },
  {
    id: "auto-0130-49954183af",
    name: "武罚",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1333 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1333, count: 10, regionLabel: "南疆" },
  },
  {
    id: "auto-0131-df8375635d",
    name: "贾富",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 52 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 52, count: 8, regionLabel: "南疆" },
  },
  {
    id: "auto-0132-4047a7497a",
    name: "古月蛮石",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 115 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 115, count: 2, regionLabel: "南疆" },
  },
  {
    id: "auto-0133-cb193a6027",
    name: "房沉",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1541 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1541, count: 4, regionLabel: "西漠" },
  },
  {
    id: "auto-0134-d3fb639ad9",
    name: "熊骄嫚",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 134 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 134, count: 3, regionLabel: "南疆" },
  },
  {
    id: "auto-0135-1d99d226ce",
    name: "石磊",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 732 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 732, count: 6, regionLabel: "中洲" },
  },
  {
    id: "auto-0136-7cd541e1ca",
    name: "武雨伯",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1324 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1324, count: 3, regionLabel: "南疆" },
  },
  {
    id: "auto-0137-30ca838aa3",
    name: "石淼",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1747 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1747, count: 3, regionLabel: "东海" },
  },
  {
    id: "auto-0138-9e3489a9b1",
    name: "毒蝎娘子",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 444 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 444, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0139-fb755901f3",
    name: "烈魔仙",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 865 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 865, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0140-d2be79f09f",
    name: "金珠仙王",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1733 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1733, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0141-cb384a048d",
    name: "黑凡",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 964 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 964, count: 22, regionLabel: "北原" },
  },
  {
    id: "auto-0142-7ec0b51abc",
    name: "监天塔主",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 863 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 863, count: 15, regionLabel: "中洲" },
  },
  {
    id: "auto-0143-e100d51ae0",
    name: "战部渡",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1846 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1846, count: 7, regionLabel: "待考" },
  },
  {
    id: "auto-0144-24e65d5e68",
    name: "百岁童子",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 352 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 352, count: 64, regionLabel: "待考" },
  },
  {
    id: "auto-0145-7e0e5b18bd",
    name: "青仇",
    region: "western",
    faction: "西漠归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入西漠。首次出现第 1540 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1540, count: 8, regionLabel: "西漠" },
  },
  {
    id: "auto-0146-ae8ecd243e",
    name: "黄沙",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 471 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 471, count: 17, regionLabel: "待考" },
  },
  {
    id: "auto-0147-a415e3dd1a",
    name: "砚石老人",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 479 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 479, count: 6, regionLabel: "南疆" },
  },
  {
    id: "auto-0148-8a7e6d86cd",
    name: "回风子",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 796 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 796, count: 6, regionLabel: "北原" },
  },
  {
    id: "auto-0149-614ea199b4",
    name: "巨开碑",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 314 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 314, count: 4, regionLabel: "南疆" },
  },
  {
    id: "auto-0150-c9b3d93b39",
    name: "药皇",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 774 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 774, count: 4, regionLabel: "北原" },
  },
  {
    id: "auto-0151-b80c612ae7",
    name: "万海龙流",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1070 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1070, count: 6, regionLabel: "待考" },
  },
  {
    id: "auto-0152-777ef1bd1c",
    name: "碧晨天",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 975 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 975, count: 8, regionLabel: "中洲" },
  },
  {
    id: "auto-0153-50e812484c",
    name: "马英杰",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 500 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 500, count: 7, regionLabel: "北原" },
  },
  {
    id: "auto-0154-7ce3dc1af4",
    name: "雪松子",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 703 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 703, count: 4, regionLabel: "北原" },
  },
  {
    id: "auto-0155-77b8210b82",
    name: "蜂将",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1911 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1911, count: 3, regionLabel: "东海" },
  },
  {
    id: "auto-0156-3093fdb8ae",
    name: "铁霸修",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 368 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 368, count: 4, regionLabel: "南疆" },
  },
  {
    id: "auto-0157-141eaa5430",
    name: "廿二富",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 1124 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1124, count: 4, regionLabel: "北原" },
  },
  {
    id: "auto-0158-4fe4980097",
    name: "耶律群星",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 1221 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1221, count: 4, regionLabel: "北原" },
  },
  {
    id: "auto-0159-1d61c1b456",
    name: "炎突",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 322 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 322, count: 3, regionLabel: "南疆" },
  },
  {
    id: "auto-0160-4bc852fdc7",
    name: "古凉",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1863 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1863, count: 10, regionLabel: "待考" },
  },
  {
    id: "auto-0161-31ee0b74a7",
    name: "血海老祖",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 191 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 191, count: 30, regionLabel: "待考" },
  },
  {
    id: "auto-0162-947bf60dd6",
    name: "铁区中",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 1638 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1638, count: 3, regionLabel: "南疆" },
  },
  {
    id: "auto-0163-3384bd6f1f",
    name: "星象地灵",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 868 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 868, count: 27, regionLabel: "待考" },
  },
  {
    id: "auto-0164-65e3c3e9b1",
    name: "古月冻土",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 109 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 109, count: 2, regionLabel: "南疆" },
  },
  {
    id: "auto-0165-c95d5929b6",
    name: "廿二平之",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 1213 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1213, count: 2, regionLabel: "北原" },
  },
  {
    id: "auto-0166-dfcf122e3b",
    name: "铁刀苦",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 229 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 229, count: 4, regionLabel: "南疆" },
  },
  {
    id: "auto-0167-09e529ff75",
    name: "小蝶",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 252 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 252, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0168-691d5ba104",
    name: "商螭吻",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 317 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 317, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0169-63a678fa00",
    name: "商蒲牢",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 338 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 338, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0170-90dc1b3ddb",
    name: "铁慕白",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 381 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 381, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0171-c9d53a5677",
    name: "气相",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1664 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1664, count: 1, regionLabel: "东海" },
  },
  {
    id: "auto-0172-d4a39b6806",
    name: "奚雪",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 550 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 550, count: 3, regionLabel: "待考" },
  },
  {
    id: "auto-0173-a3fcb77a30",
    name: "土头驮",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1672 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1672, count: 2, regionLabel: "东海" },
  },
  {
    id: "auto-0174-781343ae50",
    name: "红袖",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 764 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 764, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0175-71cfaa095c",
    name: "李逍遥",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 912 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 912, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0176-c7d733f23b",
    name: "七星子",
    region: "central",
    faction: "中洲归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入中洲。首次出现第 742 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 742, count: 3, regionLabel: "中洲" },
  },
  {
    id: "auto-0177-bbd33b34fe",
    name: "青岳安",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1723 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1723, count: 2, regionLabel: "东海" },
  },
  {
    id: "auto-0178-8b6afcaf93",
    name: "康巴",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1067 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1067, count: 6, regionLabel: "待考" },
  },
  {
    id: "auto-0179-02a5252d51",
    name: "古月药乐",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 155 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 155, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0180-4177b2e288",
    name: "商嘲风",
    region: "southern",
    faction: "南疆归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入南疆。首次出现第 336 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 336, count: 1, regionLabel: "南疆" },
  },
  {
    id: "auto-0181-7d0673cbde",
    name: "黑柏",
    region: "northern",
    faction: "北原归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入北原。首次出现第 530 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 530, count: 1, regionLabel: "北原" },
  },
  {
    id: "auto-0182-7144eb1b3b",
    name: "鬼七爷",
    region: "eastern",
    faction: "东海归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入东海。首次出现第 1912 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1912, count: 1, regionLabel: "东海" },
  },
  {
    id: "auto-0183-4b5693cc13",
    name: "夜天狼君",
    region: "black",
    faction: "太古黑天归档",
    role: "人物档案",
    intro: "原文人物档案，按出身或主要势力根基归入太古黑天。首次出现第 1992 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1992, count: 1, regionLabel: "太古黑天" },
  },
  {
    id: "auto-0184-f866d85f78",
    name: "旋空童子",
    region: "unverified",
    faction: "地域待考",
    role: "称号人物",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1741 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1741, count: 19, regionLabel: "待考" },
  },
  {
    id: "auto-0185-d380efa273",
    name: "百陌行",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 223 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 223, count: 4, regionLabel: "待考" },
  },
  {
    id: "auto-0186-9b15abcbb1",
    name: "陈双全",
    region: "unverified",
    faction: "地域待考",
    role: "人物档案",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 260 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 260, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0187-7ac7ed710b",
    name: "尸爆雷王",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 947 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 947, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0188-e0793ca165",
    name: "丹仙",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1148 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1148, count: 2, regionLabel: "待考" },
  },
  {
    id: "auto-0189-9247634258",
    name: "白光刀客",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 372 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 372, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0190-cfa1d1b7be",
    name: "火工龙头",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 857 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 857, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0191-4a9f6f6e06",
    name: "蒋基",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1145 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1145, count: 1, regionLabel: "待考" },
  },
  {
    id: "auto-0192-5aaee69543",
    name: "夜煞女",
    region: "unverified",
    faction: "地域待考",
    role: "全文候选",
    intro: "原文已出现，地域归属尚待逐条复核。首次出现第 1443 章。",
    gu: [],
    moves: [],
    houses: [],
    relations: [],
    source: { firstChapter: 1443, count: 1, regionLabel: "待考" },
  },
];

export const atlasSourceSummary = {
  title: "《蛊真人》EPUB 全文检索",
  chapterCount: 2342,
  confirmedCount: 228,
};

export const characterEvidenceByName = {
  "元莲仙尊": {
    firstChapter: 171,
    lastChapter: 2364,
    count: 343,
    chapters: 58,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "乐土仙尊": {
    firstChapter: 471,
    lastChapter: 2356,
    count: 549,
    chapters: 85,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "元始仙尊": {
    firstChapter: 615,
    lastChapter: 2365,
    count: 378,
    chapters: 43,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "千变老祖": {
    firstChapter: 1415,
    lastChapter: 2093,
    count: 310,
    chapters: 28,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "长毛老祖": {
    firstChapter: 471,
    lastChapter: 2330,
    count: 356,
    chapters: 55,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "白凝冰": {
    firstChapter: 9,
    lastChapter: 2286,
    count: 3902,
    chapters: 397,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "气海老祖": {
    firstChapter: 1665,
    lastChapter: 2360,
    count: 1622,
    chapters: 122,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "绿蚁居士": {
    firstChapter: 1851,
    lastChapter: 2164,
    count: 46,
    chapters: 7,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "明皓仙子": {
    firstChapter: 2182,
    lastChapter: 2231,
    count: 94,
    chapters: 15,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "万寿娘子": {
    firstChapter: 830,
    lastChapter: 1299,
    count: 13,
    chapters: 8,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "幻灭仙子": {
    firstChapter: 967,
    lastChapter: 1212,
    count: 4,
    chapters: 2,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "商心慈": {
    firstChapter: 243,
    lastChapter: 2319,
    count: 1083,
    chapters: 100,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "黑楼兰": {
    firstChapter: 438,
    lastChapter: 2312,
    count: 3748,
    chapters: 485,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "马鸿运": {
    firstChapter: 514,
    lastChapter: 1307,
    count: 56,
    chapters: 33,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "红莲魔尊": {
    firstChapter: 392,
    lastChapter: 2354,
    count: 396,
    chapters: 60,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "白晴仙子": {
    firstChapter: 417,
    lastChapter: 2333,
    count: 246,
    chapters: 27,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "盗天魔尊": {
    firstChapter: 445,
    lastChapter: 2355,
    count: 635,
    chapters: 89,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "琅琊地灵": {
    firstChapter: 472,
    lastChapter: 2330,
    count: 3215,
    chapters: 183,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "星宿仙尊": {
    firstChapter: 478,
    lastChapter: 2365,
    count: 3147,
    chapters: 182,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "黎山仙子": {
    firstChapter: 672,
    lastChapter: 1133,
    count: 1288,
    chapters: 114,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "凤仙太子": {
    firstChapter: 753,
    lastChapter: 2354,
    count: 769,
    chapters: 68,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "白兔姑娘": {
    firstChapter: 1233,
    lastChapter: 2272,
    count: 461,
    chapters: 59,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "雷鬼真君": {
    firstChapter: 1575,
    lastChapter: 2320,
    count: 273,
    chapters: 31,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "焚天魔女": {
    firstChapter: 760,
    lastChapter: 1502,
    count: 12,
    chapters: 7,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "冰晶仙王": {
    firstChapter: 1991,
    lastChapter: 2207,
    count: 12,
    chapters: 6,
    regionLabel: "太古黑天",
    status: "原著检索已确认",
  },
  "花酒行者": {
    firstChapter: 12,
    lastChapter: 2164,
    count: 208,
    chapters: 59,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "天鹤上人": {
    firstChapter: 200,
    lastChapter: 2249,
    count: 508,
    chapters: 34,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "幽魂魔尊": {
    firstChapter: 433,
    lastChapter: 2365,
    count: 1388,
    chapters: 145,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "巨阳仙尊": {
    firstChapter: 437,
    lastChapter: 2365,
    count: 2770,
    chapters: 225,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "紫山真君": {
    firstChapter: 629,
    lastChapter: 2110,
    count: 1009,
    chapters: 82,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "雪胡老祖": {
    firstChapter: 652,
    lastChapter: 2218,
    count: 893,
    chapters: 90,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "无极魔尊": {
    firstChapter: 955,
    lastChapter: 2351,
    count: 510,
    chapters: 60,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "紫薇仙子": {
    firstChapter: 1070,
    lastChapter: 2351,
    count: 2961,
    chapters: 223,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "妙音仙子": {
    firstChapter: 1234,
    lastChapter: 2272,
    count: 423,
    chapters: 64,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "方源": {
    firstChapter: 9,
    lastChapter: 2365,
    count: 2284,
    chapters: 899,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "方正": {
    firstChapter: 14,
    lastChapter: 2364,
    count: 292,
    chapters: 100,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "赵怜云": {
    firstChapter: 514,
    lastChapter: 2364,
    count: 82,
    chapters: 35,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "骷髅姥姥": {
    firstChapter: 1997,
    lastChapter: 2027,
    count: 3,
    chapters: 2,
    regionLabel: "太古白天",
    status: "原著检索已确认",
  },
  "萧荷尖": {
    firstChapter: 2019,
    lastChapter: 2321,
    count: 19,
    chapters: 15,
    regionLabel: "太古黑天",
    status: "原著检索已确认",
  },
  "黄史上人": {
    firstChapter: 1425,
    lastChapter: 1829,
    count: 145,
    chapters: 11,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "狂蛮魔尊": {
    firstChapter: 611,
    lastChapter: 2313,
    count: 156,
    chapters: 27,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "毓秀仙子": {
    firstChapter: 2190,
    lastChapter: 2213,
    count: 90,
    chapters: 16,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "凤金煌": {
    firstChapter: 373,
    lastChapter: 2354,
    count: 958,
    chapters: 130,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "苏白曼": {
    firstChapter: 763,
    lastChapter: 1832,
    count: 15,
    chapters: 10,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "多宝真人": {
    firstChapter: 477,
    lastChapter: 477,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "空绝老仙": {
    firstChapter: 612,
    lastChapter: 2254,
    count: 11,
    chapters: 11,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "苍郁仙子": {
    firstChapter: 684,
    lastChapter: 906,
    count: 61,
    chapters: 8,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "翠波仙子": {
    firstChapter: 1415,
    lastChapter: 2062,
    count: 96,
    chapters: 12,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "花蝶女仙": {
    firstChapter: 1172,
    lastChapter: 1924,
    count: 23,
    chapters: 8,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "太白云生": {
    firstChapter: 436,
    lastChapter: 1788,
    count: 2094,
    chapters: 281,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "凤九歌": {
    firstChapter: 417,
    lastChapter: 2332,
    count: 142,
    chapters: 73,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "吴帅": {
    firstChapter: 1849,
    lastChapter: 2360,
    count: 103,
    chapters: 53,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "大梦仙尊": {
    firstChapter: 472,
    lastChapter: 2354,
    count: 81,
    chapters: 7,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "狐仙地灵": {
    firstChapter: 374,
    lastChapter: 1132,
    count: 35,
    chapters: 12,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "影无邪": {
    firstChapter: 987,
    lastChapter: 2101,
    count: 48,
    chapters: 26,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "火原洞主": {
    firstChapter: 2129,
    lastChapter: 2154,
    count: 52,
    chapters: 4,
    regionLabel: "太古白天",
    status: "原著检索已确认",
  },
  "姜钰": {
    firstChapter: 707,
    lastChapter: 1184,
    count: 138,
    chapters: 21,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "萧家老祖": {
    firstChapter: 980,
    lastChapter: 1018,
    count: 9,
    chapters: 3,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "江牙": {
    firstChapter: 20,
    lastChapter: 115,
    count: 5,
    chapters: 2,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "贾金生": {
    firstChapter: 50,
    lastChapter: 63,
    count: 13,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "百八十奴": {
    firstChapter: 1395,
    lastChapter: 1395,
    count: 2,
    chapters: 1,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "古月空井": {
    firstChapter: 96,
    lastChapter: 96,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "阳骏": {
    firstChapter: 1713,
    lastChapter: 1713,
    count: 1,
    chapters: 1,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "铁若男": {
    firstChapter: 178,
    lastChapter: 2318,
    count: 502,
    chapters: 59,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月方想": {
    firstChapter: 2273,
    lastChapter: 2330,
    count: 3,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "林大鸟": {
    firstChapter: 949,
    lastChapter: 949,
    count: 2,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "叶凡": {
    firstChapter: 696,
    lastChapter: 2091,
    count: 33,
    chapters: 14,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "东方长凡": {
    firstChapter: 675,
    lastChapter: 1209,
    count: 22,
    chapters: 13,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "商一帆": {
    firstChapter: 330,
    lastChapter: 2149,
    count: 2,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "武庸": {
    firstChapter: 1238,
    lastChapter: 2293,
    count: 102,
    chapters: 62,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "龙公": {
    firstChapter: 1254,
    lastChapter: 2210,
    count: 176,
    chapters: 94,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "陆畏因": {
    firstChapter: 1430,
    lastChapter: 2250,
    count: 77,
    chapters: 40,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "百草率": {
    firstChapter: 225,
    lastChapter: 225,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "百陌亭": {
    firstChapter: 225,
    lastChapter: 225,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "百盛景": {
    firstChapter: 226,
    lastChapter: 226,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "史宏": {
    firstChapter: 846,
    lastChapter: 846,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "二毛": {
    firstChapter: 900,
    lastChapter: 900,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "黑心道人": {
    firstChapter: 1739,
    lastChapter: 1739,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "钟义": {
    firstChapter: 2126,
    lastChapter: 2126,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "白沧水": {
    firstChapter: 889,
    lastChapter: 2352,
    count: 20,
    chapters: 12,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "童画": {
    firstChapter: 1321,
    lastChapter: 1934,
    count: 38,
    chapters: 9,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "宋紫星": {
    firstChapter: 722,
    lastChapter: 2110,
    count: 25,
    chapters: 8,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "秦鼎菱": {
    firstChapter: 1847,
    lastChapter: 2364,
    count: 59,
    chapters: 37,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "黑城": {
    firstChapter: 539,
    lastChapter: 1145,
    count: 34,
    chapters: 16,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "房睇长": {
    firstChapter: 1542,
    lastChapter: 2303,
    count: 55,
    chapters: 34,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "厉煌": {
    firstChapter: 1654,
    lastChapter: 1834,
    count: 44,
    chapters: 21,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "秦百胜": {
    firstChapter: 693,
    lastChapter: 1049,
    count: 43,
    chapters: 25,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "陈衣": {
    firstChapter: 1530,
    lastChapter: 1869,
    count: 39,
    chapters: 29,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "沈伤": {
    firstChapter: 1930,
    lastChapter: 2294,
    count: 36,
    chapters: 20,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "韩立": {
    firstChapter: 688,
    lastChapter: 1435,
    count: 13,
    chapters: 8,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "墨瑶": {
    firstChapter: 581,
    lastChapter: 1034,
    count: 26,
    chapters: 13,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "乔丝柳": {
    firstChapter: 1238,
    lastChapter: 1647,
    count: 23,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "楚度": {
    firstChapter: 1075,
    lastChapter: 2248,
    count: 29,
    chapters: 18,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "沈从声": {
    firstChapter: 1722,
    lastChapter: 2246,
    count: 32,
    chapters: 17,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "人祖": {
    firstChapter: 13,
    lastChapter: 2204,
    count: 20,
    chapters: 11,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "池曲由": {
    firstChapter: 1402,
    lastChapter: 1954,
    count: 27,
    chapters: 17,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "百莲": {
    firstChapter: 225,
    lastChapter: 227,
    count: 7,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "古月阴荒": {
    firstChapter: 189,
    lastChapter: 604,
    count: 6,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "君神光": {
    firstChapter: 1626,
    lastChapter: 2294,
    count: 5,
    chapters: 4,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "常丽": {
    firstChapter: 591,
    lastChapter: 628,
    count: 8,
    chapters: 3,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "气绝魔仙": {
    firstChapter: 2022,
    lastChapter: 2240,
    count: 18,
    chapters: 11,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "赤舌": {
    firstChapter: 101,
    lastChapter: 101,
    count: 3,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "江鹤": {
    firstChapter: 77,
    lastChapter: 77,
    count: 2,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "苏仙儿": {
    firstChapter: 539,
    lastChapter: 961,
    count: 3,
    chapters: 3,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "房棱": {
    firstChapter: 1526,
    lastChapter: 2290,
    count: 36,
    chapters: 15,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "毛六": {
    firstChapter: 1092,
    lastChapter: 2272,
    count: 23,
    chapters: 16,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "商睚眦": {
    firstChapter: 270,
    lastChapter: 319,
    count: 9,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "薄青": {
    firstChapter: 972,
    lastChapter: 1654,
    count: 23,
    chapters: 13,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "房功": {
    firstChapter: 1549,
    lastChapter: 2293,
    count: 25,
    chapters: 15,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "万紫红": {
    firstChapter: 1737,
    lastChapter: 2363,
    count: 21,
    chapters: 13,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "百足天君": {
    firstChapter: 781,
    lastChapter: 2282,
    count: 12,
    chapters: 9,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "鹤风扬": {
    firstChapter: 219,
    lastChapter: 720,
    count: 15,
    chapters: 6,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "白相": {
    firstChapter: 1053,
    lastChapter: 2087,
    count: 40,
    chapters: 12,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "贺狼子": {
    firstChapter: 768,
    lastChapter: 997,
    count: 17,
    chapters: 12,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "任修平": {
    firstChapter: 1174,
    lastChapter: 2007,
    count: 16,
    chapters: 12,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "宋启元": {
    firstChapter: 1712,
    lastChapter: 1952,
    count: 18,
    chapters: 11,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "房云": {
    firstChapter: 1526,
    lastChapter: 2128,
    count: 17,
    chapters: 11,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "古月博": {
    firstChapter: 66,
    lastChapter: 199,
    count: 16,
    chapters: 10,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "车尾": {
    firstChapter: 1739,
    lastChapter: 2364,
    count: 18,
    chapters: 12,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "陈鑫": {
    firstChapter: 242,
    lastChapter: 260,
    count: 3,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "皮水寒": {
    firstChapter: 799,
    lastChapter: 1727,
    count: 19,
    chapters: 11,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "古月赤练": {
    firstChapter: 12,
    lastChapter: 163,
    count: 13,
    chapters: 9,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "自在书生": {
    firstChapter: 768,
    lastChapter: 1127,
    count: 5,
    chapters: 5,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "庙明神": {
    firstChapter: 1317,
    lastChapter: 1934,
    count: 18,
    chapters: 8,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "洪易": {
    firstChapter: 691,
    lastChapter: 1969,
    count: 15,
    chapters: 13,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "夏槎": {
    firstChapter: 1621,
    lastChapter: 1919,
    count: 14,
    chapters: 8,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "魏央": {
    firstChapter: 272,
    lastChapter: 372,
    count: 12,
    chapters: 10,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "苏琪涵": {
    firstChapter: 1892,
    lastChapter: 2148,
    count: 11,
    chapters: 3,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "马尊": {
    firstChapter: 449,
    lastChapter: 1347,
    count: 13,
    chapters: 9,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "古月药红": {
    firstChapter: 90,
    lastChapter: 90,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "张阴": {
    firstChapter: 1712,
    lastChapter: 2050,
    count: 11,
    chapters: 9,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "李然": {
    firstChapter: 288,
    lastChapter: 297,
    count: 14,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月药姬": {
    firstChapter: 85,
    lastChapter: 179,
    count: 12,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月青书": {
    firstChapter: 147,
    lastChapter: 2086,
    count: 12,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月一代": {
    firstChapter: 192,
    lastChapter: 861,
    count: 10,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "巴十八": {
    firstChapter: 1748,
    lastChapter: 2318,
    count: 10,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "寒灰仙姑": {
    firstChapter: 1991,
    lastChapter: 2052,
    count: 4,
    chapters: 2,
    regionLabel: "太古黑天",
    status: "原著检索已确认",
  },
  "毛十二": {
    firstChapter: 903,
    lastChapter: 2330,
    count: 12,
    chapters: 8,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "石宗": {
    firstChapter: 1480,
    lastChapter: 2321,
    count: 14,
    chapters: 10,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "万象星君": {
    firstChapter: 681,
    lastChapter: 870,
    count: 8,
    chapters: 6,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "熊力": {
    firstChapter: 129,
    lastChapter: 249,
    count: 7,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "张柱": {
    firstChapter: 246,
    lastChapter: 253,
    count: 6,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "商青青": {
    firstChapter: 1129,
    lastChapter: 1179,
    count: 4,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "容婆": {
    firstChapter: 1710,
    lastChapter: 2050,
    count: 11,
    chapters: 7,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "古月漠尘": {
    firstChapter: 29,
    lastChapter: 183,
    count: 6,
    chapters: 5,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "华语老仙": {
    firstChapter: 2030,
    lastChapter: 2305,
    count: 8,
    chapters: 7,
    regionLabel: "太古白天",
    status: "原著检索已确认",
  },
  "池伤": {
    firstChapter: 1349,
    lastChapter: 2104,
    count: 14,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "曾落子": {
    firstChapter: 1672,
    lastChapter: 1925,
    count: 10,
    chapters: 4,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "卫德馨": {
    firstChapter: 338,
    lastChapter: 2152,
    count: 11,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "乔志材": {
    firstChapter: 1360,
    lastChapter: 1404,
    count: 10,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "宋亦诗": {
    firstChapter: 914,
    lastChapter: 2129,
    count: 7,
    chapters: 4,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "萧芒": {
    firstChapter: 402,
    lastChapter: 1057,
    count: 9,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "武八重": {
    firstChapter: 2009,
    lastChapter: 2253,
    count: 8,
    chapters: 6,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "常极右": {
    firstChapter: 546,
    lastChapter: 603,
    count: 7,
    chapters: 6,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "易酒仙姑": {
    firstChapter: 1851,
    lastChapter: 1867,
    count: 2,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "萧山": {
    firstChapter: 980,
    lastChapter: 1020,
    count: 10,
    chapters: 5,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "武独秀": {
    firstChapter: 1235,
    lastChapter: 1362,
    count: 5,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "熊姜": {
    firstChapter: 129,
    lastChapter: 143,
    count: 4,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月赤城": {
    firstChapter: 12,
    lastChapter: 90,
    count: 6,
    chapters: 5,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月漠北": {
    firstChapter: 12,
    lastChapter: 89,
    count: 8,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "夏飞快": {
    firstChapter: 1328,
    lastChapter: 1332,
    count: 8,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "熊林": {
    firstChapter: 143,
    lastChapter: 197,
    count: 5,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "房化生": {
    firstChapter: 1549,
    lastChapter: 2288,
    count: 5,
    chapters: 4,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "武罚": {
    firstChapter: 1333,
    lastChapter: 1342,
    count: 10,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "贾富": {
    firstChapter: 52,
    lastChapter: 65,
    count: 8,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古月蛮石": {
    firstChapter: 115,
    lastChapter: 142,
    count: 2,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "房沉": {
    firstChapter: 1541,
    lastChapter: 2288,
    count: 4,
    chapters: 3,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "熊骄嫚": {
    firstChapter: 134,
    lastChapter: 197,
    count: 3,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "石磊": {
    firstChapter: 732,
    lastChapter: 1241,
    count: 6,
    chapters: 2,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "武雨伯": {
    firstChapter: 1324,
    lastChapter: 1330,
    count: 3,
    chapters: 2,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "石淼": {
    firstChapter: 1747,
    lastChapter: 1946,
    count: 3,
    chapters: 2,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "毒蝎娘子": {
    firstChapter: 444,
    lastChapter: 444,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "烈魔仙": {
    firstChapter: 865,
    lastChapter: 865,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "金珠仙王": {
    firstChapter: 1733,
    lastChapter: 1733,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "黑凡": {
    firstChapter: 964,
    lastChapter: 1437,
    count: 22,
    chapters: 9,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "监天塔主": {
    firstChapter: 863,
    lastChapter: 1036,
    count: 15,
    chapters: 9,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "战部渡": {
    firstChapter: 1846,
    lastChapter: 2228,
    count: 7,
    chapters: 4,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "铁血冷": {
    firstChapter: 178,
    lastChapter: 193,
    count: 8,
    chapters: 7,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "百岁童子": {
    firstChapter: 352,
    lastChapter: 613,
    count: 64,
    chapters: 10,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "青仇": {
    firstChapter: 1540,
    lastChapter: 2052,
    count: 8,
    chapters: 5,
    regionLabel: "西漠",
    status: "原著检索已确认",
  },
  "黄沙": {
    firstChapter: 471,
    lastChapter: 1482,
    count: 17,
    chapters: 6,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "砚石老人": {
    firstChapter: 479,
    lastChapter: 1019,
    count: 6,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "回风子": {
    firstChapter: 796,
    lastChapter: 1128,
    count: 6,
    chapters: 4,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "巨开碑": {
    firstChapter: 314,
    lastChapter: 329,
    count: 4,
    chapters: 4,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "药皇": {
    firstChapter: 774,
    lastChapter: 2233,
    count: 4,
    chapters: 4,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "万海龙流": {
    firstChapter: 1070,
    lastChapter: 1355,
    count: 6,
    chapters: 6,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "碧晨天": {
    firstChapter: 975,
    lastChapter: 1306,
    count: 8,
    chapters: 5,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "马英杰": {
    firstChapter: 500,
    lastChapter: 591,
    count: 7,
    chapters: 5,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "雪松子": {
    firstChapter: 703,
    lastChapter: 893,
    count: 4,
    chapters: 3,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "蜂将": {
    firstChapter: 1911,
    lastChapter: 1922,
    count: 3,
    chapters: 3,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "铁霸修": {
    firstChapter: 368,
    lastChapter: 378,
    count: 4,
    chapters: 2,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "廿二富": {
    firstChapter: 1124,
    lastChapter: 1126,
    count: 4,
    chapters: 2,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "耶律群星": {
    firstChapter: 1221,
    lastChapter: 1482,
    count: 4,
    chapters: 2,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "炎突": {
    firstChapter: 322,
    lastChapter: 323,
    count: 3,
    chapters: 2,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "古凉": {
    firstChapter: 1863,
    lastChapter: 1866,
    count: 10,
    chapters: 4,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "血海老祖": {
    firstChapter: 191,
    lastChapter: 2304,
    count: 30,
    chapters: 12,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "商燕飞": {
    firstChapter: 275,
    lastChapter: 319,
    count: 4,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "铁区中": {
    firstChapter: 1638,
    lastChapter: 1812,
    count: 3,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "星象地灵": {
    firstChapter: 868,
    lastChapter: 988,
    count: 27,
    chapters: 12,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "古月冻土": {
    firstChapter: 109,
    lastChapter: 120,
    count: 2,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "廿二平之": {
    firstChapter: 1213,
    lastChapter: 1215,
    count: 2,
    chapters: 1,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "铁刀苦": {
    firstChapter: 229,
    lastChapter: 306,
    count: 4,
    chapters: 3,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "小蝶": {
    firstChapter: 252,
    lastChapter: 252,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "商螭吻": {
    firstChapter: 317,
    lastChapter: 317,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "商蒲牢": {
    firstChapter: 338,
    lastChapter: 338,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "铁慕白": {
    firstChapter: 381,
    lastChapter: 381,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "气相": {
    firstChapter: 1664,
    lastChapter: 1664,
    count: 1,
    chapters: 1,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "奚雪": {
    firstChapter: 550,
    lastChapter: 618,
    count: 3,
    chapters: 3,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "土头驮": {
    firstChapter: 1672,
    lastChapter: 1674,
    count: 2,
    chapters: 2,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "红袖": {
    firstChapter: 764,
    lastChapter: 765,
    count: 2,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "李逍遥": {
    firstChapter: 912,
    lastChapter: 926,
    count: 2,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "七星子": {
    firstChapter: 742,
    lastChapter: 1015,
    count: 3,
    chapters: 1,
    regionLabel: "中洲",
    status: "原著检索已确认",
  },
  "青岳安": {
    firstChapter: 1723,
    lastChapter: 1959,
    count: 2,
    chapters: 1,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "康巴": {
    firstChapter: 1067,
    lastChapter: 1067,
    count: 6,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "古月药乐": {
    firstChapter: 155,
    lastChapter: 155,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "商嘲风": {
    firstChapter: 336,
    lastChapter: 336,
    count: 1,
    chapters: 1,
    regionLabel: "南疆",
    status: "原著检索已确认",
  },
  "黑柏": {
    firstChapter: 530,
    lastChapter: 530,
    count: 1,
    chapters: 1,
    regionLabel: "北原",
    status: "原著检索已确认",
  },
  "鬼七爷": {
    firstChapter: 1912,
    lastChapter: 1912,
    count: 1,
    chapters: 1,
    regionLabel: "东海",
    status: "原著检索已确认",
  },
  "夜天狼君": {
    firstChapter: 1992,
    lastChapter: 1992,
    count: 1,
    chapters: 1,
    regionLabel: "太古黑天",
    status: "原著检索已确认",
  },
  "旋空童子": {
    firstChapter: 1741,
    lastChapter: 1981,
    count: 19,
    chapters: 10,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "百陌行": {
    firstChapter: 223,
    lastChapter: 227,
    count: 4,
    chapters: 2,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "陈双全": {
    firstChapter: 260,
    lastChapter: 260,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "尸爆雷王": {
    firstChapter: 947,
    lastChapter: 947,
    count: 2,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "丹仙": {
    firstChapter: 1148,
    lastChapter: 1334,
    count: 2,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "白光刀客": {
    firstChapter: 372,
    lastChapter: 372,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "火工龙头": {
    firstChapter: 857,
    lastChapter: 857,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "蒋基": {
    firstChapter: 1145,
    lastChapter: 1145,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
  "夜煞女": {
    firstChapter: 1443,
    lastChapter: 1443,
    count: 1,
    chapters: 1,
    regionLabel: "待考",
    status: "原著检索已确认",
  },
};
